test:
    JENKINS_URL: "http://jenkins.mxnet-ci-dev.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'test-jenkins-run-statistics'
    DYNAMODB_TABLE_NAME: 'test-jenkins-run-statistics'

prod:
    JENKINS_URL: "http://jenkins.mxnet-ci.amazon-ml.com/"
    REGION: us-west-2
    CLOUDWATCH_METRIC_NAMESPACE: 'JenkinsRunStatistics'
    DYNAMODB_TABLE_NAME: 'JenkinsRunStatistics'

